export const books = [
    {
        id:1,
        title:"The Three Musketeers",
        author:"Alexandre Dumas",
        category:"adventure",
        img: "./images/1.jpg",
    },
    {
        id:2,
        title:"The Jungle Book",
        author:"Rudyard Kipling",
        category:"adventure",
        img:"./images/2.jpg",
    },
    {
        id:3,
        title:"Adventures of Huckleberry Finn",
        author:"Mark Twain",
        category:"adventure",
        img:"./images/3.jpg",
    },
    {
        id:4,
        title:"Shantaram",
        author:"Gregory David Roberts",
        category:"adventure",
        img:"./images/4.jpg",
    },
    {
        id:5,
        title:"Steve Jobs",
        author:"Walter Isaacson",
        category:"Biography",
        img:"./images/5.jpg",
    },
    {
        id:6,
        title:"The Diary of a Young Girl",
        author:"Anne Frank",
        category:"Biography",
        img:"./images/6.jpg",
    },
    {
        id:7,
        title:"Becoming",
        author:"Michelle Obama",
        category:"Biography",
        img:"./images/7.jpg",
    },
    {
        id:8,
        title:"Born a Crime",
        author:"Trevor Noah",
        category:"Biography",
        img:"./images/8.jpg",
    },
    {
        id:9,
        title:"And Then There Were None",
        author:"Agatha Christie",
        category:"Mystery",
        img:"./images/9.jpg",
    },
    {
        id:10,
        title:"Where the Crawdads Sing",
        author:"Delia Owens",
        category:"Mystery",
        img:"./images/10.jpg",
    },
    {
        id:11,
        title:"In the Woods",
        author:"Tana French",
        category:"Mystery",
        img:"./images/11.jpg",
    },
    {
        id:12,
        title:"The Da Vinci Code",
        author:"Dan Brown",
        category:"Mystery",
        img:"./images/12.jpg",
    },
];